spring.application.name=Invoice_Management_SPRING_REACT_PSQL

spring.datasource.url=jdbc:postgresql://0.0.0.0:5432/invoice_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.expiration-ms=86400000
